name: SitPlugin
version: ${project.version}
main: de.marvinleiers.sitplugin.SitPlugin
api-version: 1.16
authors: [ Marvin_Leiers ]
website: www.marvinleiers.de

commands:
  sit:
    description: Sit down
